recommended_medication(amyotrophic-lateral-sclerosis-als, 'riluzole').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'baclofen').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'tizanidine').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'glycopyrrolate').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'celecoxib_(celebrex)').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'vitamin_e_(vita_e)').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'quinine').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'ubiquinone_(q10)').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'fibrin_sealant_topical').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'beta_carotene').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'creatine').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'dantrolene').
recommended_medication(amyotrophic-lateral-sclerosis-als, 'coal_tar_topical').

recommended_medication(tension-headache, 'topiramate_(topamax)').
recommended_medication(tension-headache, 'midrin').
recommended_medication(tension-headache, 'rizatriptan_(maxalt)').
recommended_medication(tension-headache, 'eletriptan_(relpax)').
recommended_medication(tension-headache, 'butorphanol_(stadol)').
recommended_medication(tension-headache, 'diclofenac_topical_product').
recommended_medication(tension-headache, 'piroxicam').
recommended_medication(tension-headache, 'monobenzone_topical').

recommended_medication(migraine, 'sumatriptan_(imitrex)').
recommended_medication(migraine, 'topiramate_(topamax)').
recommended_medication(migraine, 'prochlorperazine_(compro)').
recommended_medication(migraine, 'rizatriptan_(maxalt)').
recommended_medication(migraine, 'nalbuphine_(nubain)').
recommended_medication(migraine, 'propranolol').
recommended_medication(migraine, 'eletriptan_(relpax)').
recommended_medication(migraine, 'midrin').
recommended_medication(migraine, 'zolmitriptan_(zomig)').
recommended_medication(migraine, 'nortriptyline').
recommended_medication(migraine, 'butorphanol_(stadol)').

recommended_medication(parkinson-disease, 'ropinirole').
recommended_medication(parkinson-disease, 'pramipexole_(mirapex)').
recommended_medication(parkinson-disease, 'amantadine').
recommended_medication(parkinson-disease, 'donepezil_(aricept)').
recommended_medication(parkinson-disease, 'rasagiline_(azilect)').
recommended_medication(parkinson-disease, 'carbidopa').
recommended_medication(parkinson-disease, 'entacapone_(comtan)').
recommended_medication(parkinson-disease, 'memantine_(namenda)').
recommended_medication(parkinson-disease, 'selegiline').
recommended_medication(parkinson-disease, 'trihexyphenidyl_(artane)').
recommended_medication(parkinson-disease, 'rivastigmine_(exelon)').

recommended_medication(dementia, 'donepezil_(aricept)').
recommended_medication(dementia, 'memantine_(namenda)').
recommended_medication(dementia, 'rivastigmine_(exelon)').
recommended_medication(dementia, 'galantamine').
recommended_medication(dementia, 'mirtazapine').
recommended_medication(dementia, 'thiamine').
recommended_medication(dementia, 'pramipexole_(mirapex)').
recommended_medication(dementia, 'felodipine').
recommended_medication(dementia, 'bisacodyl_(the_magic_bullet)').
recommended_medication(dementia, 'modafinil_(provigil)').
recommended_medication(dementia, 'raloxifene_(evista)').
recommended_medication(dementia, 'deferasirox_(exjade)').

recommended_medication(multiple-sclerosis, 'interferon_beta_1a_(avonex)').
recommended_medication(multiple-sclerosis, 'glatiramer_(copaxone)').
recommended_medication(multiple-sclerosis, 'baclofen').
recommended_medication(multiple-sclerosis, 'modafinil_(provigil)').
recommended_medication(multiple-sclerosis, 'oxybutynin').
recommended_medication(multiple-sclerosis, 'tizanidine').
recommended_medication(multiple-sclerosis, 'natalizumab_(tysabri)').
recommended_medication(multiple-sclerosis, 'tolterodine_(detrol)').
recommended_medication(multiple-sclerosis, 'amantadine').
recommended_medication(multiple-sclerosis, 'solifenacin_(vesicare)').
recommended_medication(multiple-sclerosis, 'azathioprine').
recommended_medication(multiple-sclerosis, 'cyclophosphamide').
recommended_medication(multiple-sclerosis, 'armodafinil_(nuvigil)').

recommended_medication(alzheimer-disease, 'donepezil_(aricept)').
recommended_medication(alzheimer-disease, 'memantine_(namenda)').
recommended_medication(alzheimer-disease, 'rivastigmine_(exelon)').
recommended_medication(alzheimer-disease, 'galantamine').
recommended_medication(alzheimer-disease, 'dapiprazole_ophthalmic').
recommended_medication(alzheimer-disease, 'alendronate_cholecalciferol').
recommended_medication(alzheimer-disease, 'bromocriptine').
recommended_medication(alzheimer-disease, 'fluvastatin_(lescol)').
recommended_medication(alzheimer-disease, 'citric_acid').
recommended_medication(alzheimer-disease, 'astemizole').
recommended_medication(alzheimer-disease, 'hypromellose_(genteal)').

recommended_medication(epilepsy, 'levetiracetam_(keppra)').
recommended_medication(epilepsy, 'phenytoin_(dilantin)').
recommended_medication(epilepsy, 'lamotrigine_(lamictal)').
recommended_medication(epilepsy, 'divalproex_sodium_(depakote)').
recommended_medication(epilepsy, 'carbamazepine').
recommended_medication(epilepsy, 'topiramate_(topamax)').
recommended_medication(epilepsy, 'oxcarbazepine_(trileptal)').
recommended_medication(epilepsy, 'phenobarbital').
recommended_medication(epilepsy, 'zonisamide').
recommended_medication(epilepsy, 'valproic_acid').
recommended_medication(epilepsy, 'fosphenytoin').
recommended_medication(epilepsy, 'ethosuximide').
recommended_medication(epilepsy, 'lacosamide_(vimpat)').

recommended_medication(meningitis, 'ceftriaxone').
recommended_medication(meningitis, 'vancomycin').
recommended_medication(meningitis, 'ampicillin').
recommended_medication(meningitis, 'prochlorperazine_(compro)').
recommended_medication(meningitis, 'midazolam_(versed)').
recommended_medication(meningitis, 'cefotaxime').
recommended_medication(meningitis, 'acyclovir').
recommended_medication(meningitis, 'phenobarbital').
recommended_medication(meningitis, 'gentamicin_ophthalmic').
recommended_medication(meningitis, 'cefuroxime').
recommended_medication(meningitis, 'micafungin').
recommended_medication(meningitis, 'amphotericin_b').
recommended_medication(meningitis, 'tapentadol_(nucynta)').

